In [3]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [4]:
import os

In [24]:
a=pd.read_csv('HRAttrition.csv')
a

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7
10,35,No,Travel_Rarely,809,Research & Development,16,3,Medical,1,14,...,3,80,1,6,5,3,5,4,0,3
11,29,No,Travel_Rarely,153,Research & Development,15,2,Life Sciences,1,15,...,4,80,0,10,3,3,9,5,0,8
12,31,No,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,16,...,4,80,1,5,1,2,5,2,4,3
13,34,No,Travel_Rarely,1346,Research & Development,19,2,Medical,1,18,...,3,80,1,3,2,3,2,2,1,2
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
15,29,No,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,1,20,...,3,80,1,10,1,3,10,9,8,8
16,32,No,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,...,4,80,2,7,5,2,6,2,0,5
17,22,No,Non-Travel,1123,Research & Development,16,2,Medical,1,22,...,2,80,2,1,2,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
19,38,No,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,...,3,80,0,6,3,3,3,2,1,2
20,24,No,Non-Travel,673,Research & Development,11,2,Other,1,26,...,4,80,1,5,5,2,4,2,1,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
22,34,No,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,...,3,80,0,13,4,3,12,6,2,11
23,21,No,Travel_Rarely,391,Research & Development,15,2,Life Sciences,1,30,...,4,80,0,0,6,3,0,0,0,0
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
27,42,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,...,4,80,1,10,2,3,9,7,4,2
28,44,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,...,4,80,1,24,4,3,22,6,5,17
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,No,Travel_Frequently,688,Research & Development,4,2,Life Sciences,1,2025,...,2,80,3,18,3,3,4,2,0,2
1441,56,No,Non-Travel,667,Research & Development,1,4,Life Sciences,1,2026,...,1,80,1,13,2,2,13,12,1,9
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1443,42,No,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,2031,...,1,80,0,24,2,2,22,6,4,14
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1445,41,No,Travel_Rarely,582,Research & Development,28,4,Life Sciences,1,2034,...,3,80,1,21,3,3,20,7,0,10
1446,34,No,Travel_Rarely,704,Sales,28,3,Marketing,1,2035,...,4,80,2,8,2,3,8,7,1,7
1447,36,No,Non-Travel,301,Sales,15,4,Marketing,1,2036,...,1,80,1,15,4,2,15,12,11,11
1448,41,No,Travel_Rarely,930,Sales,3,3,Life Sciences,1,2037,...,3,80,1,14,5,3,5,4,0,4
1449,32,No,Travel_Rarely,529,Research & Development,2,3,Technical Degree,1,2038,...,4,80,0,4,4,3,4,2,1,2
1450,35,No,Travel_Rarely,1146,Human Resources,26,4,Life Sciences,1,2040,...,3,80,0,9,2,3,9,0,1,7
1451,38,No,Travel_Rarely,345,Sales,10,2,Life Sciences,1,2041,...,3,80,1,10,1,3,10,7,1,9
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1453,36,No,Travel_Rarely,1120,Sales,11,4,Marketing,1,2045,...,1,80,1,8,2,2,6,3,0,0
1454,45,No,Travel_Rarely,374,Sales,20,3,Life Sciences,1,2046,...,3,80,0,8,3,3,5,3,0,1
1455,40,No,Travel_Rarely,1322,Research & Development,2,4,Life Sciences,1,2048,...,4,80,0,8,2,3,2,2,2,2
1456,35,No,Travel_Frequently,1199,Research & Development,18,4,Life Sciences,1,2049,...,4,80,2,10,2,4,10,2,0,2
1457,40,No,Travel_Rarely,1194,Research & Development,2,4,Medical,1,2051,...,2,80,3,20,2,3,5,3,0,2
1458,35,No,Travel_Rarely,287,Research & Development,1,4,Life Sciences,1,2052,...,4,80,1,4,5,3,4,3,1,1
1459,29,No,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,...,1,80,1,10,2,3,4,3,0,3
1460,29,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,...,2,80,0,5,3,1,5,4,0,4
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6
1463,31,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,...,2,80,0,10,2,3,9,4,1,7
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [17]:
df=a
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7
10,35,No,Travel_Rarely,809,Research & Development,16,3,Medical,1,14,...,3,80,1,6,5,3,5,4,0,3
11,29,No,Travel_Rarely,153,Research & Development,15,2,Life Sciences,1,15,...,4,80,0,10,3,3,9,5,0,8
12,31,No,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,16,...,4,80,1,5,1,2,5,2,4,3
13,34,No,Travel_Rarely,1346,Research & Development,19,2,Medical,1,18,...,3,80,1,3,2,3,2,2,1,2
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
15,29,No,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,1,20,...,3,80,1,10,1,3,10,9,8,8
16,32,No,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,...,4,80,2,7,5,2,6,2,0,5
17,22,No,Non-Travel,1123,Research & Development,16,2,Medical,1,22,...,2,80,2,1,2,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
19,38,No,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,...,3,80,0,6,3,3,3,2,1,2
20,24,No,Non-Travel,673,Research & Development,11,2,Other,1,26,...,4,80,1,5,5,2,4,2,1,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
22,34,No,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,...,3,80,0,13,4,3,12,6,2,11
23,21,No,Travel_Rarely,391,Research & Development,15,2,Life Sciences,1,30,...,4,80,0,0,6,3,0,0,0,0
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
27,42,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,...,4,80,1,10,2,3,9,7,4,2
28,44,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,...,4,80,1,24,4,3,22,6,5,17
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,No,Travel_Frequently,688,Research & Development,4,2,Life Sciences,1,2025,...,2,80,3,18,3,3,4,2,0,2
1441,56,No,Non-Travel,667,Research & Development,1,4,Life Sciences,1,2026,...,1,80,1,13,2,2,13,12,1,9
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1443,42,No,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,2031,...,1,80,0,24,2,2,22,6,4,14
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1445,41,No,Travel_Rarely,582,Research & Development,28,4,Life Sciences,1,2034,...,3,80,1,21,3,3,20,7,0,10
1446,34,No,Travel_Rarely,704,Sales,28,3,Marketing,1,2035,...,4,80,2,8,2,3,8,7,1,7
1447,36,No,Non-Travel,301,Sales,15,4,Marketing,1,2036,...,1,80,1,15,4,2,15,12,11,11
1448,41,No,Travel_Rarely,930,Sales,3,3,Life Sciences,1,2037,...,3,80,1,14,5,3,5,4,0,4
1449,32,No,Travel_Rarely,529,Research & Development,2,3,Technical Degree,1,2038,...,4,80,0,4,4,3,4,2,1,2
1450,35,No,Travel_Rarely,1146,Human Resources,26,4,Life Sciences,1,2040,...,3,80,0,9,2,3,9,0,1,7
1451,38,No,Travel_Rarely,345,Sales,10,2,Life Sciences,1,2041,...,3,80,1,10,1,3,10,7,1,9
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1453,36,No,Travel_Rarely,1120,Sales,11,4,Marketing,1,2045,...,1,80,1,8,2,2,6,3,0,0
1454,45,No,Travel_Rarely,374,Sales,20,3,Life Sciences,1,2046,...,3,80,0,8,3,3,5,3,0,1
1455,40,No,Travel_Rarely,1322,Research & Development,2,4,Life Sciences,1,2048,...,4,80,0,8,2,3,2,2,2,2
1456,35,No,Travel_Frequently,1199,Research & Development,18,4,Life Sciences,1,2049,...,4,80,2,10,2,4,10,2,0,2
1457,40,No,Travel_Rarely,1194,Research & Development,2,4,Medical,1,2051,...,2,80,3,20,2,3,5,3,0,2
1458,35,No,Travel_Rarely,287,Research & Development,1,4,Life Sciences,1,2052,...,4,80,1,4,5,3,4,3,1,1
1459,29,No,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,...,1,80,1,10,2,3,4,3,0,3
1460,29,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,...,2,80,0,5,3,1,5,4,0,4
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6
1463,31,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,...,2,80,0,10,2,3,9,4,1,7
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [18]:
df.head(0)

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]

In [19]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [20]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [23]:
d=df
d

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,...,2,80,0,7,3,3,0,0,0,0
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,...,3,80,0,8,3,3,8,7,3,0
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,...,4,80,1,6,3,3,2,2,2,2
5,32,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,4,...,3,80,0,8,2,2,7,7,3,6
6,59,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,3,...,1,80,3,12,3,2,1,0,0,0
7,30,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,4,...,2,80,1,1,2,3,1,0,0,0
8,38,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,4,...,2,80,0,10,2,3,9,7,1,8
9,36,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,3,...,2,80,2,17,3,2,7,7,7,7
10,35,Travel_Rarely,809,Research & Development,16,3,Medical,1,14,1,...,3,80,1,6,5,3,5,4,0,3
11,29,Travel_Rarely,153,Research & Development,15,2,Life Sciences,1,15,4,...,4,80,0,10,3,3,9,5,0,8
12,31,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,16,1,...,4,80,1,5,1,2,5,2,4,3
13,34,Travel_Rarely,1346,Research & Development,19,2,Medical,1,18,2,...,3,80,1,3,2,3,2,2,1,2
14,28,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,3,...,2,80,0,6,4,3,4,2,0,3
15,29,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,1,20,2,...,3,80,1,10,1,3,10,9,8,8
16,32,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,1,...,4,80,2,7,5,2,6,2,0,5
17,22,Non-Travel,1123,Research & Development,16,2,Medical,1,22,4,...,2,80,2,1,2,2,1,0,0,0
18,53,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,1,...,3,80,0,31,3,3,25,8,3,7
19,38,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,4,...,3,80,0,6,3,3,3,2,1,2
20,24,Non-Travel,673,Research & Development,11,2,Other,1,26,1,...,4,80,1,5,5,2,4,2,1,3
21,36,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,3,...,2,80,0,10,4,3,5,3,0,3
22,34,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,1,...,3,80,0,13,4,3,12,6,2,11
23,21,Travel_Rarely,391,Research & Development,15,2,Life Sciences,1,30,3,...,4,80,0,0,6,3,0,0,0,0
24,34,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,2,...,3,80,0,8,2,3,4,2,1,3
25,53,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,3,...,4,80,1,26,3,2,14,13,4,8
26,32,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,2,...,2,80,0,10,5,3,10,2,6,7
27,42,Travel_Rarely,691,Sales,8,4,Marketing,1,35,3,...,4,80,1,10,2,3,9,7,4,2
28,44,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,1,...,4,80,1,24,4,3,22,6,5,17
29,46,Travel_Rarely,705,Sales,2,4,Marketing,1,38,2,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,Travel_Frequently,688,Research & Development,4,2,Life Sciences,1,2025,4,...,2,80,3,18,3,3,4,2,0,2
1441,56,Non-Travel,667,Research & Development,1,4,Life Sciences,1,2026,3,...,1,80,1,13,2,2,13,12,1,9
1442,29,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,1,...,2,80,3,4,3,4,2,2,2,2
1443,42,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,2031,1,...,1,80,0,24,2,2,22,6,4,14
1444,56,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,4,...,4,80,1,14,4,1,10,9,9,8
1445,41,Travel_Rarely,582,Research & Development,28,4,Life Sciences,1,2034,1,...,3,80,1,21,3,3,20,7,0,10
1446,34,Travel_Rarely,704,Sales,28,3,Marketing,1,2035,4,...,4,80,2,8,2,3,8,7,1,7
1447,36,Non-Travel,301,Sales,15,4,Marketing,1,2036,4,...,1,80,1,15,4,2,15,12,11,11
1448,41,Travel_Rarely,930,Sales,3,3,Life Sciences,1,2037,3,...,3,80,1,14,5,3,5,4,0,4
1449,32,Travel_Rarely,529,Research & Development,2,3,Technical Degree,1,2038,4,...,4,80,0,4,4,3,4,2,1,2
1450,35,Travel_Rarely,1146,Human Resources,26,4,Life Sciences,1,2040,3,...,3,80,0,9,2,3,9,0,1,7
1451,38,Travel_Rarely,345,Sales,10,2,Life Sciences,1,2041,1,...,3,80,1,10,1,3,10,7,1,9
1452,50,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,2,...,4,80,2,12,3,3,6,3,0,1
1453,36,Travel_Rarely,1120,Sales,11,4,Marketing,1,2045,2,...,1,80,1,8,2,2,6,3,0,0
1454,45,Travel_Rarely,374,Sales,20,3,Life Sciences,1,2046,4,...,3,80,0,8,3,3,5,3,0,1
1455,40,Travel_Rarely,1322,Research & Development,2,4,Life Sciences,1,2048,3,...,4,80,0,8,2,3,2,2,2,2
1456,35,Travel_Frequently,1199,Research & Development,18,4,Life Sciences,1,2049,3,...,4,80,2,10,2,4,10,2,0,2
1457,40,Travel_Rarely,1194,Research & Development,2,4,Medical,1,2051,3,...,2,80,3,20,2,3,5,3,0,2
1458,35,Travel_Rarely,287,Research & Development,1,4,Life Sciences,1,2052,3,...,4,80,1,4,5,3,4,3,1,1
1459,29,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,4,...,1,80,1,10,2,3,4,3,0,3
1460,29,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,4,...,2,80,0,5,3,1,5,4,0,4
1461,50,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,4,...,2,80,1,20,3,3,3,2,2,0
1462,39,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,2,...,1,80,1,21,2,2,20,9,9,6
1463,31,Non-Travel,325,Research & Development,5,3,Medical,1,2057,2,...,2,80,0,10,2,3,9,4,1,7
1464,26,Travel_Rarely,1167,Sales,5,3,Other,1,2060,4,...,4,80,0,5,2,3,4,2,0,0
1465,36,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,3,...,3,80,1,17,3,3,5,2,0,3
1466,39,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,4,...,1,80,1,9,5,3,7,7,1,7
1467,27,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,4,...,4,80,0,17,3,2,9,6,0,8
1469,34,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,2,...,1,80,0,6,3,4,4,3,1,2

In [58]:
b=pd.read_csv('HRAttrition.csv')
b

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7
10,35,No,Travel_Rarely,809,Research & Development,16,3,Medical,1,14,...,3,80,1,6,5,3,5,4,0,3
11,29,No,Travel_Rarely,153,Research & Development,15,2,Life Sciences,1,15,...,4,80,0,10,3,3,9,5,0,8
12,31,No,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,16,...,4,80,1,5,1,2,5,2,4,3
13,34,No,Travel_Rarely,1346,Research & Development,19,2,Medical,1,18,...,3,80,1,3,2,3,2,2,1,2
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
15,29,No,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,1,20,...,3,80,1,10,1,3,10,9,8,8
16,32,No,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,...,4,80,2,7,5,2,6,2,0,5
17,22,No,Non-Travel,1123,Research & Development,16,2,Medical,1,22,...,2,80,2,1,2,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
19,38,No,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,...,3,80,0,6,3,3,3,2,1,2
20,24,No,Non-Travel,673,Research & Development,11,2,Other,1,26,...,4,80,1,5,5,2,4,2,1,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
22,34,No,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,...,3,80,0,13,4,3,12,6,2,11
23,21,No,Travel_Rarely,391,Research & Development,15,2,Life Sciences,1,30,...,4,80,0,0,6,3,0,0,0,0
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
27,42,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,...,4,80,1,10,2,3,9,7,4,2
28,44,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,...,4,80,1,24,4,3,22,6,5,17
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,No,Travel_Frequently,688,Research & Development,4,2,Life Sciences,1,2025,...,2,80,3,18,3,3,4,2,0,2
1441,56,No,Non-Travel,667,Research & Development,1,4,Life Sciences,1,2026,...,1,80,1,13,2,2,13,12,1,9
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1443,42,No,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,2031,...,1,80,0,24,2,2,22,6,4,14
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1445,41,No,Travel_Rarely,582,Research & Development,28,4,Life Sciences,1,2034,...,3,80,1,21,3,3,20,7,0,10
1446,34,No,Travel_Rarely,704,Sales,28,3,Marketing,1,2035,...,4,80,2,8,2,3,8,7,1,7
1447,36,No,Non-Travel,301,Sales,15,4,Marketing,1,2036,...,1,80,1,15,4,2,15,12,11,11
1448,41,No,Travel_Rarely,930,Sales,3,3,Life Sciences,1,2037,...,3,80,1,14,5,3,5,4,0,4
1449,32,No,Travel_Rarely,529,Research & Development,2,3,Technical Degree,1,2038,...,4,80,0,4,4,3,4,2,1,2
1450,35,No,Travel_Rarely,1146,Human Resources,26,4,Life Sciences,1,2040,...,3,80,0,9,2,3,9,0,1,7
1451,38,No,Travel_Rarely,345,Sales,10,2,Life Sciences,1,2041,...,3,80,1,10,1,3,10,7,1,9
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1453,36,No,Travel_Rarely,1120,Sales,11,4,Marketing,1,2045,...,1,80,1,8,2,2,6,3,0,0
1454,45,No,Travel_Rarely,374,Sales,20,3,Life Sciences,1,2046,...,3,80,0,8,3,3,5,3,0,1
1455,40,No,Travel_Rarely,1322,Research & Development,2,4,Life Sciences,1,2048,...,4,80,0,8,2,3,2,2,2,2
1456,35,No,Travel_Frequently,1199,Research & Development,18,4,Life Sciences,1,2049,...,4,80,2,10,2,4,10,2,0,2
1457,40,No,Travel_Rarely,1194,Research & Development,2,4,Medical,1,2051,...,2,80,3,20,2,3,5,3,0,2
1458,35,No,Travel_Rarely,287,Research & Development,1,4,Life Sciences,1,2052,...,4,80,1,4,5,3,4,3,1,1
1459,29,No,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,...,1,80,1,10,2,3,4,3,0,3
1460,29,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,...,2,80,0,5,3,1,5,4,0,4
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6
1463,31,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,...,2,80,0,10,2,3,9,4,1,7
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [27]:
x=b[['Age','BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager']]
y=b['Attrition']

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x, y, stratify=y, test_size= 0.15,random_state=1)

In [30]:
# Decision Tree - Entropy
modelDecisionTreeEntropy = DecisionTreeClassifier(criterion='entropy', max_depth=4)
modelDecisionTreeEntropy.fit(X_train,y_train)
predDTEntropy = modelDecisionTreeEntropy.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predDTEntropy)
cnf_matrix
print("Accuracy Decision Tree Entropy:",metrics.accuracy_score(y_test, predDTEntropy))

ValueError: could not convert string to float: 'Travel_Rarely'

In [38]:
v=pd.get_dummies(x[['Department','BusinessTravel','EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime']])
v

,Department_Human Resources,Department_Research & Development,Department_Sales,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0,0,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,1,1,0,1
1,0,1,0,0,1,0,0,1,0,0,...,0,1,0,0,0,1,0,1,1,0
2,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1
3,0,1,0,0,1,0,0,1,0,0,...,0,1,0,0,0,1,0,1,0,1
4,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
5,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,1,1,1,0
6,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,0,1
7,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,1,1,0
8,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,1,1,1,0
9,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
10,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
11,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,1,0,1
12,0,1,0,0,0,1,0,1,0,0,...,0,1,0,0,1,0,0,1,1,0
13,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,1,0,0,1,1,0
14,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,1,0,1
15,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,1,1,0
16,0,1,0,0,0,1,0,1,0,0,...,0,1,0,0,1,0,0,1,0,1
17,0,1,0,1,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,1
18,0,0,1,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,1,1,0
19,0,1,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,1,1,0,1
20,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,1,0
21,0,0,1,0,0,1,0,1,0,0,...,0,0,0,1,0,0,1,1,1,0
22,0,1,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,1,1,1,0
23,0,1,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,1,1,1,0
24,0,1,0,0,0,1,0,0,0,1,...,0,1,0,0,0,0,1,1,1,0
25,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,1,0
26,0,1,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,1,1,0,1
27,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,1,1,0
28,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
29,0,0,1,0,0,1,0,0,1,0,...,0,0,0,0,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,1,1,0
1441,0,1,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,1,1,0
1442,0,1,0,0,0,1,0,0,0,1,...,0,1,0,0,0,1,0,1,0,1
1443,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,1,1,0
1444,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
1445,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,1,1,0
1446,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,1,1,0
1447,0,0,1,1,0,0,0,0,1,0,...,0,0,1,0,1,0,0,1,1,0
1448,0,0,1,0,0,1,0,1,0,0,...,0,0,1,0,1,0,0,1,1,0
1449,0,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,1,1,0
1450,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,1,0,1
1451,0,0,1,0,0,1,0,1,0,0,...,0,0,1,0,0,1,0,1,1,0
1452,0,0,1,0,1,0,0,1,0,0,...,0,0,1,0,1,0,0,1,1,0
1453,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,1,1,0
1454,0,0,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,1,1,1,0
1455,0,1,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,1,1,1,0
1456,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,1
1457,0,1,0,0,0,1,0,0,0,1,...,0,1,0,0,0,1,0,1,1,0
1458,0,1,0,0,0,1,0,1,0,0,...,0,1,0,0,0,1,0,1,1,0
1459,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,1
1460,0,1,0,0,0,1,0,0,0,1,...,0,1,0,0,0,0,1,1,1,0
1461,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,1,0,0,1,0,1
1462,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,1,1,0
1463,0,1,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,1,1,1,0
1464,0,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,1,1,0
1465,0,1,0,0,1,0,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
1466,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
1467,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,1,0,1
1468,0,0,1,0,1,0,0,0,0,1,...,0,0,1,0,0,1,0,1,1,0
1469,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0

In [83]:
x=0
for i in b['BusinessTravel']:
    if (i=='Travel_Frequently'):
        i=1
    if i=='Travel_Rarely':
        i=0
    print(i);print(x)
        
        
        #lis.append(i)
    #print(i)

0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
Non-Travel
0
Non-Travel
0
1
0
0
0
0
0
0
0
1
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
Non-Travel
0
Non-Travel
0
0
0
1
0
Non-Travel
0
0
0
0
0
1
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
1
0
0
0
1
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
Non-Travel
0
1
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
Non-Travel
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
1
0
Non-Travel
0
1
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
Non-Travel
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
0
0
Non-Travel
0
1
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
Non-Travel
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
Non-Travel
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
1
0
Non-Travel
0
Non-Travel
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
1
0
Non-Travel
0
0
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
1
0
Non-Travel
0
Non-Travel
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
Non-Travel
0
Non-Travel
0
1
0
0
0
1
0
0
0
1
0
1
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
Non-Travel
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
Non-Travel
0
1
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
1
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
1
0
Non-Travel
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
1
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
Non-Travel
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
Non-Travel
0
0
0
Non-Travel
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
Non-Travel
0
1
0
0
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
1
0
1
0
1
0
1
0
Non-Travel
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
1
0
1
0
Non-Travel
0
0
0
1
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
Non-Travel
0
Non-Travel
0
Non-Travel
0
0
0
0
0
0
0
0
0
Non-Travel
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
Non-Travel
0
Non-Travel
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
1
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
Non-Travel
0
1
0
0
0
1
0
Non-Travel
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
Non-Travel
0
0
0
1
0
0
0
0
0
1
0
0
0

In [80]:
e='squaressss'
e.count('s')

5

In [69]:
x['new']=b['BusinessTravel']
x['new']

0           Travel_Rarely
1       Travel_Frequently
2           Travel_Rarely
3       Travel_Frequently
4           Travel_Rarely
5       Travel_Frequently
6           Travel_Rarely
7           Travel_Rarely
8       Travel_Frequently
9           Travel_Rarely
10          Travel_Rarely
11          Travel_Rarely
12          Travel_Rarely
13          Travel_Rarely
14          Travel_Rarely
15          Travel_Rarely
16          Travel_Rarely
17             Non-Travel
18          Travel_Rarely
19          Travel_Rarely
20             Non-Travel
21          Travel_Rarely
22          Travel_Rarely
23          Travel_Rarely
24          Travel_Rarely
25          Travel_Rarely
26      Travel_Frequently
27          Travel_Rarely
28          Travel_Rarely
29          Travel_Rarely
              ...
1440    Travel_Frequently
1441           Non-Travel
1442        Travel_Rarely
1443        Travel_Rarely
1444        Travel_Rarely
1445        Travel_Rarely
1446        Travel_Rarely
1447           Non-Travel
1448        Travel_Rarely
1449        Travel_Rarely
1450        Travel_Rarely
1451        Travel_Rarely
1452    Travel_Frequently
1453        Travel_Rarely
1454        Travel_Rarely
1455        Travel_Rarely
1456    Travel_Frequently
1457        Travel_Rarely
1458        Travel_Rarely
1459        Travel_Rarely
1460        Travel_Rarely
1461        Travel_Rarely
1462        Travel_Rarely
1463           Non-Travel
1464        Travel_Rarely
1465    Travel_Frequently
1466        Travel_Rarely
1467        Travel_Rarely
1468    Travel_Frequently
1469        Travel_Rarely
Name: new, Length: 1470, dtype: object

In [59]:
b['BusinessTravel']

0           Travel_Rarely
1       Travel_Frequently
2           Travel_Rarely
3       Travel_Frequently
4           Travel_Rarely
5       Travel_Frequently
6           Travel_Rarely
7           Travel_Rarely
8       Travel_Frequently
9           Travel_Rarely
10          Travel_Rarely
11          Travel_Rarely
12          Travel_Rarely
13          Travel_Rarely
14          Travel_Rarely
15          Travel_Rarely
16          Travel_Rarely
17             Non-Travel
18          Travel_Rarely
19          Travel_Rarely
20             Non-Travel
21          Travel_Rarely
22          Travel_Rarely
23          Travel_Rarely
24          Travel_Rarely
25          Travel_Rarely
26      Travel_Frequently
27          Travel_Rarely
28          Travel_Rarely
29          Travel_Rarely
              ...
1440    Travel_Frequently
1441           Non-Travel
1442        Travel_Rarely
1443        Travel_Rarely
1444        Travel_Rarely
1445        Travel_Rarely
1446        Travel_Rarely
1447           Non-Travel
1448        Travel_Rarely
1449        Travel_Rarely
1450        Travel_Rarely
1451        Travel_Rarely
1452    Travel_Frequently
1453        Travel_Rarely
1454        Travel_Rarely
1455        Travel_Rarely
1456    Travel_Frequently
1457        Travel_Rarely
1458        Travel_Rarely
1459        Travel_Rarely
1460        Travel_Rarely
1461        Travel_Rarely
1462        Travel_Rarely
1463           Non-Travel
1464        Travel_Rarely
1465    Travel_Frequently
1466        Travel_Rarely
1467        Travel_Rarely
1468    Travel_Frequently
1469        Travel_Rarely
Name: BusinessTravel, Length: 1470, dtype: object

In [37]:
c=x.drop(['Department','BusinessTravel','EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime'],axis=1)
c

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2
5,32,1005,2,2,1,8,4,79,3,1,...,3,80,0,8,2,2,7,7,3,6
6,59,1324,3,3,1,10,3,81,4,1,...,1,80,3,12,3,2,1,0,0,0
7,30,1358,24,1,1,11,4,67,3,1,...,2,80,1,1,2,3,1,0,0,0
8,38,216,23,3,1,12,4,44,2,3,...,2,80,0,10,2,3,9,7,1,8
9,36,1299,27,3,1,13,3,94,3,2,...,2,80,2,17,3,2,7,7,7,7
10,35,809,16,3,1,14,1,84,4,1,...,3,80,1,6,5,3,5,4,0,3
11,29,153,15,2,1,15,4,49,2,2,...,4,80,0,10,3,3,9,5,0,8
12,31,670,26,1,1,16,1,31,3,1,...,4,80,1,5,1,2,5,2,4,3
13,34,1346,19,2,1,18,2,93,3,1,...,3,80,1,3,2,3,2,2,1,2
14,28,103,24,3,1,19,3,50,2,1,...,2,80,0,6,4,3,4,2,0,3
15,29,1389,21,4,1,20,2,51,4,3,...,3,80,1,10,1,3,10,9,8,8
16,32,334,5,2,1,21,1,80,4,1,...,4,80,2,7,5,2,6,2,0,5
17,22,1123,16,2,1,22,4,96,4,1,...,2,80,2,1,2,2,1,0,0,0
18,53,1219,2,4,1,23,1,78,2,4,...,3,80,0,31,3,3,25,8,3,7
19,38,371,2,3,1,24,4,45,3,1,...,3,80,0,6,3,3,3,2,1,2
20,24,673,11,2,1,26,1,96,4,2,...,4,80,1,5,5,2,4,2,1,3
21,36,1218,9,4,1,27,3,82,2,1,...,2,80,0,10,4,3,5,3,0,3
22,34,419,7,4,1,28,1,53,3,3,...,3,80,0,13,4,3,12,6,2,11
23,21,391,15,2,1,30,3,96,3,1,...,4,80,0,0,6,3,0,0,0,0
24,34,699,6,1,1,31,2,83,3,1,...,3,80,0,8,2,3,4,2,1,3
25,53,1282,5,3,1,32,3,58,3,5,...,4,80,1,26,3,2,14,13,4,8
26,32,1125,16,1,1,33,2,72,1,1,...,2,80,0,10,5,3,10,2,6,7
27,42,691,8,4,1,35,3,48,3,2,...,4,80,1,10,2,3,9,7,4,2
28,44,477,7,4,1,36,1,42,2,3,...,4,80,1,24,4,3,22,6,5,17
29,46,705,2,4,1,38,2,83,3,5,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,688,4,2,1,2025,4,97,3,2,...,2,80,3,18,3,3,4,2,0,2
1441,56,667,1,4,1,2026,3,57,3,2,...,1,80,1,13,2,2,13,12,1,9
1442,29,1092,1,4,1,2027,1,36,3,1,...,2,80,3,4,3,4,2,2,2,2
1443,42,300,2,3,1,2031,1,56,3,5,...,1,80,0,24,2,2,22,6,4,14
1444,56,310,7,2,1,2032,4,72,3,1,...,4,80,1,14,4,1,10,9,9,8
1445,41,582,28,4,1,2034,1,60,2,4,...,3,80,1,21,3,3,20,7,0,10
1446,34,704,28,3,1,2035,4,95,2,2,...,4,80,2,8,2,3,8,7,1,7
1447,36,301,15,4,1,2036,4,88,1,2,...,1,80,1,15,4,2,15,12,11,11
1448,41,930,3,3,1,2037,3,57,2,2,...,3,80,1,14,5,3,5,4,0,4
1449,32,529,2,3,1,2038,4,78,3,1,...,4,80,0,4,4,3,4,2,1,2
1450,35,1146,26,4,1,2040,3,31,3,3,...,3,80,0,9,2,3,9,0,1,7
1451,38,345,10,2,1,2041,1,100,3,2,...,3,80,1,10,1,3,10,7,1,9
1452,50,878,1,4,1,2044,2,94,3,2,...,4,80,2,12,3,3,6,3,0,1
1453,36,1120,11,4,1,2045,2,100,2,2,...,1,80,1,8,2,2,6,3,0,0
1454,45,374,20,3,1,2046,4,50,3,2,...,3,80,0,8,3,3,5,3,0,1
1455,40,1322,2,4,1,2048,3,52,2,1,...,4,80,0,8,2,3,2,2,2,2
1456,35,1199,18,4,1,2049,3,80,3,2,...,4,80,2,10,2,4,10,2,0,2
1457,40,1194,2,4,1,2051,3,98,3,1,...,2,80,3,20,2,3,5,3,0,2
1458,35,287,1,4,1,2052,3,62,1,1,...,4,80,1,4,5,3,4,3,1,1
1459,29,1378,13,2,1,2053,4,46,2,2,...,1,80,1,10,2,3,4,3,0,3
1460,29,468,28,4,1,2054,4,73,2,1,...,2,80,0,5,3,1,5,4,0,4
1461,50,410,28,3,1,2055,4,39,2,3,...,2,80,1,20,3,3,3,2,2,0
1462,39,722,24,1,1,2056,2,60,2,4,...,1,80,1,21,2,2,20,9,9,6
1463,31,325,5,3,1,2057,2,74,3,2,...,2,80,0,10,2,3,9,4,1,7
1464,26,1167,5,3,1,2060,4,30,2,1,...,4,80,0,5,2,3,4,2,0,0
1465,36,884,23,2,1,2061,3,41,4,2,...,3,80,1,17,3,3,5,2,0,3
1466,39,613,6,1,1,2062,4,42,2,3,...,1,80,1,9,5,3,7,7,1,7
1467,27,155,4,3,1,2064,2,87,4,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,1023,2,3,1,2065,4,63,2,2,...,4,80,0,17,3,2,9,6,0,8
1469,34,628,8,3,1,2068,2,82,4,2,...,1,80,0,6,3,4,4,3,1,2

In [40]:
d=pd.concat([c,v],axis=1)
x=d
x

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0,0,1,0,0,0,1,1,0,1
1,49,279,8,1,1,2,3,61,2,2,...,0,1,0,0,0,1,0,1,1,0
2,37,1373,2,2,1,4,4,92,2,1,...,0,0,0,0,0,0,1,1,0,1
3,33,1392,3,4,1,5,4,56,3,1,...,0,1,0,0,0,1,0,1,0,1
4,27,591,2,1,1,7,1,40,3,1,...,0,0,0,0,0,1,0,1,1,0
5,32,1005,2,2,1,8,4,79,3,1,...,0,0,0,0,0,0,1,1,1,0
6,59,1324,3,3,1,10,3,81,4,1,...,0,0,0,0,0,1,0,1,0,1
7,30,1358,24,1,1,11,4,67,3,1,...,0,0,0,0,1,0,0,1,1,0
8,38,216,23,3,1,12,4,44,2,3,...,0,0,0,0,0,0,1,1,1,0
9,36,1299,27,3,1,13,3,94,3,2,...,0,0,0,0,0,1,0,1,1,0
10,35,809,16,3,1,14,1,84,4,1,...,0,0,0,0,0,1,0,1,1,0
11,29,153,15,2,1,15,4,49,2,2,...,0,0,0,0,0,0,1,1,0,1
12,31,670,26,1,1,16,1,31,3,1,...,0,1,0,0,1,0,0,1,1,0
13,34,1346,19,2,1,18,2,93,3,1,...,0,0,0,0,1,0,0,1,1,0
14,28,103,24,3,1,19,3,50,2,1,...,0,0,0,0,0,0,1,1,0,1
15,29,1389,21,4,1,20,2,51,4,3,...,0,0,0,0,1,0,0,1,1,0
16,32,334,5,2,1,21,1,80,4,1,...,0,1,0,0,1,0,0,1,0,1
17,22,1123,16,2,1,22,4,96,4,1,...,0,0,0,0,1,0,0,1,0,1
18,53,1219,2,4,1,23,1,78,2,4,...,0,0,0,0,0,1,0,1,1,0
19,38,371,2,3,1,24,4,45,3,1,...,0,1,0,0,0,0,1,1,0,1
20,24,673,11,2,1,26,1,96,4,2,...,0,0,0,0,1,0,0,1,1,0
21,36,1218,9,4,1,27,3,82,2,1,...,0,0,0,1,0,0,1,1,1,0
22,34,419,7,4,1,28,1,53,3,3,...,1,0,0,0,0,0,1,1,1,0
23,21,391,15,2,1,30,3,96,3,1,...,0,1,0,0,0,0,1,1,1,0
24,34,699,6,1,1,31,2,83,3,1,...,0,1,0,0,0,0,1,1,1,0
25,53,1282,5,3,1,32,3,58,3,5,...,0,0,0,0,1,0,0,1,1,0
26,32,1125,16,1,1,33,2,72,1,1,...,0,1,0,0,0,0,1,1,0,1
27,42,691,8,4,1,35,3,48,3,2,...,0,0,1,0,0,1,0,1,1,0
28,44,477,7,4,1,36,1,42,2,3,...,0,0,0,0,0,1,0,1,1,0
29,46,705,2,4,1,38,2,83,3,5,...,0,0,0,0,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,688,4,2,1,2025,4,97,3,2,...,0,0,0,0,1,0,0,1,1,0
1441,56,667,1,4,1,2026,3,57,3,2,...,0,0,0,0,1,0,0,1,1,0
1442,29,1092,1,4,1,2027,1,36,3,1,...,0,1,0,0,0,1,0,1,0,1
1443,42,300,2,3,1,2031,1,56,3,5,...,0,0,0,0,0,1,0,1,1,0
1444,56,310,7,2,1,2032,4,72,3,1,...,0,0,0,0,0,1,0,1,1,0
1445,41,582,28,4,1,2034,1,60,2,4,...,0,0,0,0,0,1,0,1,1,0
1446,34,704,28,3,1,2035,4,95,2,2,...,0,0,1,0,0,1,0,1,1,0
1447,36,301,15,4,1,2036,4,88,1,2,...,0,0,1,0,1,0,0,1,1,0
1448,41,930,3,3,1,2037,3,57,2,2,...,0,0,1,0,1,0,0,1,1,0
1449,32,529,2,3,1,2038,4,78,3,1,...,0,1,0,0,0,0,1,1,1,0
1450,35,1146,26,4,1,2040,3,31,3,3,...,0,0,0,0,0,0,1,1,0,1
1451,38,345,10,2,1,2041,1,100,3,2,...,0,0,1,0,0,1,0,1,1,0
1452,50,878,1,4,1,2044,2,94,3,2,...,0,0,1,0,1,0,0,1,1,0
1453,36,1120,11,4,1,2045,2,100,2,2,...,0,0,1,0,0,1,0,1,1,0
1454,45,374,20,3,1,2046,4,50,3,2,...,0,0,1,0,0,0,1,1,1,0
1455,40,1322,2,4,1,2048,3,52,2,1,...,0,1,0,0,0,0,1,1,1,0
1456,35,1199,18,4,1,2049,3,80,3,2,...,0,0,0,0,0,1,0,1,0,1
1457,40,1194,2,4,1,2051,3,98,3,1,...,0,1,0,0,0,1,0,1,1,0
1458,35,287,1,4,1,2052,3,62,1,1,...,0,1,0,0,0,1,0,1,1,0
1459,29,1378,13,2,1,2053,4,46,2,2,...,0,0,0,0,0,1,0,1,0,1
1460,29,468,28,4,1,2054,4,73,2,1,...,0,1,0,0,0,0,1,1,1,0
1461,50,410,28,3,1,2055,4,39,2,3,...,0,0,1,0,1,0,0,1,0,1
1462,39,722,24,1,1,2056,2,60,2,4,...,0,0,1,0,0,1,0,1,1,0
1463,31,325,5,3,1,2057,2,74,3,2,...,0,0,0,0,0,0,1,1,1,0
1464,26,1167,5,3,1,2060,4,30,2,1,...,0,0,0,1,0,0,1,1,1,0
1465,36,884,23,2,1,2061,3,41,4,2,...,0,0,0,0,0,1,0,1,1,0
1466,39,613,6,1,1,2062,4,42,2,3,...,0,0,0,0,0,1,0,1,1,0
1467,27,155,4,3,1,2064,2,87,4,2,...,0,0,0,0,0,1,0,1,0,1
1468,49,1023,2,3,1,2065,4,63,2,2,...,0,0,1,0,0,1,0,1,1,0
1469,34,628,8,3,1,2068,2,82,4,2,...,0,0,0,0,0,1,0,1,1,0

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x, y, stratify=y, test_size= 0.15,random_state=1)

In [42]:
# Decision Tree - Entropy
modelDecisionTreeEntropy = DecisionTreeClassifier(criterion='entropy', max_depth=4)
modelDecisionTreeEntropy.fit(X_train,y_train)
predDTEntropy = modelDecisionTreeEntropy.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predDTEntropy)
cnf_matrix
print("Accuracy Decision Tree Entropy:",metrics.accuracy_score(y_test, predDTEntropy))

Accuracy Decision Tree Entropy: 0.8823529411764706

In [43]:
# Decision Tree - Entropy
modelDecisionTreeEntropy = DecisionTreeClassifier(criterion='entropy', max_depth=3)
modelDecisionTreeEntropy.fit(X_train,y_train)
predDTEntropy = modelDecisionTreeEntropy.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predDTEntropy)
cnf_matrix
print("Accuracy Decision Tree Entropy:",metrics.accuracy_score(y_test, predDTEntropy))

Accuracy Decision Tree Entropy: 0.8823529411764706

In [44]:
# Decision Tree - Entropy
modelDecisionTreeEntropy = DecisionTreeClassifier(criterion='entropy', max_depth=5)
modelDecisionTreeEntropy.fit(X_train,y_train)
predDTEntropy = modelDecisionTreeEntropy.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predDTEntropy)
cnf_matrix
print("Accuracy Decision Tree Entropy:",metrics.accuracy_score(y_test, predDTEntropy))

Accuracy Decision Tree Entropy: 0.8280542986425339

In [45]:
# Decision Tree - Gini
modelDecisionTreeGini = DecisionTreeClassifier(criterion='gini', max_depth=4)
modelDecisionTreeGini.fit(X_train,y_train)
predDTGini = modelDecisionTreeEntropy.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predDTGini)
cnf_matrix
print("Accuracy Decision Tree Entropy:",metrics.accuracy_score(y_test, predDTGini))

Accuracy Decision Tree Entropy: 0.8280542986425339

In [46]:
# Decision Tree - Gini
modelDecisionTreeGini = DecisionTreeClassifier(criterion='gini', max_depth=3)
modelDecisionTreeGini.fit(X_train,y_train)
predDTGini = modelDecisionTreeEntropy.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predDTGini)
cnf_matrix
print("Accuracy Decision Tree Entropy:",metrics.accuracy_score(y_test, predDTGini))

Accuracy Decision Tree Entropy: 0.8280542986425339

In [52]:
# Decision Tree - Gini
modelDecisionTreeGini = DecisionTreeClassifier(criterion='gini', max_depth=)
modelDecisionTreeGini.fit(X_train,y_train)
predDTGini = modelDecisionTreeEntropy.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predDTGini)
cnf_matrix
print("Accuracy Decision Tree Entropy:",metrics.accuracy_score(y_test, predDTGini))

Accuracy Decision Tree Entropy: 0.8280542986425339

In [48]:
# Logistic Regression
modelLogistic = LogisticRegression()
modelLogistic.fit(X_train,y_train)
predLogistic = modelLogistic.predict(X_test)
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test,predLogistic)
cnf_matrix
print("Accuracy Logistic Regression:",metrics.accuracy_score(y_test, predLogistic))

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Accuracy Logistic Regression: 0.8914027149321267